language: node_js
node_js: 14.15.0
branches:
  only:
    - develop
    - "/^release-[0-999].[0-999]$/"
    - master
addons:
  chrome: stable
  sonarcloud: true
install:
  - npm install
  - npm ci
script:
  - nohup npm run dev & sleep 3 & npm run test
  - sonar-scanner -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=alejandrorsanchez
