on:
  push:
    branches:
      - develop

name: SonarCloud Scan
jobs:
  sonarcloud:
    name: Build, Test and Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@develop
      # uses: actions/checkout@v2
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
